### ISSUE TITLE
moderators can configure pool- and project-formation algorithms using the CLI

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/game-cli#82]
## Overview

As per https://github.com/LearnersGuild/game/issues/418, the moderator needs a way to configure the pool- and project-formation algorithms. Each of these algorithms has a different relationship to Elo rankings.

The suggestion from game mechanics was two configuration "files" to be passed to `cycle init` and `cycle launch` commands. However, uploading files to echo would be difficult to support in a clean way. Engineering suggested the alternative of configuration URLs rather than files.

OND: it seems to me that one configuration file with different sections would be superior, and perhaps a moderator-only command to update the configuration makes the most sense.

### View full configuration

_moderator only_

```
@moderator > /config
@echo      > Configuration
             -------------
             pools:
               - id: green
                 elo_band: 0..1000
                 advanced_players:
                   - @bundacia
                   - @shereefb
               - id: blue
                 elo_band: 1001..2500
                 advanced_players:
                   - @jeffreywescott
                   - @prattsj
             project_limits:
               elo_0: 1
               elo_1100: 2
               elo_1300: 3
               elo_1500: 4
```

### Configure voting pools

```
@moderator > /config add --pools id:purple elo_band:2001..9999 advanced_players:[@tannerwelsh, @jeffreywescott]
@echo      > Config added.
@moderator > /config update --pools id:blue elo_band:1001..2000 advanced_players:[@jrob, @deadlyicon]
@echo      > Config updated.
@moderator > /config delete --pools id:purple
@echo      > Config deleted.
@moderator > /config get --pools
@echo      > pools:
             - id: green
               elo_band: 0..1000
               advanced_players:
                 - @bundacia
                 - @shereefb
             - id: blue
               elo_band: 1001..2000
               advanced_players:
                 - @jrob
                 - @deadlyicon
```

### Set concurrent projects limit

```
@moderator > /config add --project_limits elo_1200:2
@echo      > Config added.
@moderator > /config update --project_limits elo_1500:5
@echo      > Config updated.
@moderator > /config delete --project_limits elo_1100
@echo      > Config deleted.
@moderator > /config get --project_limits
@echo      > project_limits:
               elo_0: 1
               elo_1200: 2
               elo_1300: 3
               elo_1500: 5
```

#### Top-level command

```
@moderator > /config --help
@echo      > /config - game settings
 
             Usage:
                 /config [options] <command>
 
             Commands:
                 get            - View a game setting
                 
                 add            - Add a game setting
                 
                 update         - Change a game setting

                 delete         - Remove a game setting
 
             Options:
                 --help, -h            print usage information
                 --pools, -p           configure voting pools
                 --project_limits, -l  configure concurrent project limits
 
 
             Examples:
                 # Add a new voting pool
                 /config add --pools id:purple elo_band:2001..9999 advanced_players:[@tannerwelsh, @jeffreywescott] 
                 
                 # Update the concurrent project limits for players with Elo >= 1500
                 /config update --project_limits elo_1500:5
```

#### Example subcommand

```
@moderator > /config add --help
@echo      > /config add - game settings
 
             Usage:
                 /config add <options> <data>
 
             Options:
                 --help, -h            print usage information
                 --pools, -p           add a voting pools
                 --project_limits, -l  add a concurrent project limits
```

## Configuration Format

Arguments to command. No file upload.

## Feedback to Moderator

- Successful commands respond with simple success message.
- Invalid/unparseable respond with standard error message, directing to `--help`
- Moderator can view all config settings at any time with `/config` or `/config get [opts]`

## Player Visibility of Configuration

Not visible. Voting pools and concurrent project limits may be made visible through other means. `/config` command is only accessible to a moderator.

**Comment by jeffreywescott** [comment]
## Open UX Issues

- How should the moderator re-configure the game? What command + arguments should be used?
- Will there be configuration "files" or "URLs"? If so, what is the file format for the configuration? YAML?
- What feedback should be given to the moderator from the command once its issued?
- Is the configuration information public / private? In other words, can non-moderators "view" it somehow?

**Comment by jeffreywescott** [comment]
@tannerwelsh LMK if this works as a starting-point for UX work. Ideally, I'd like to provide something like this for everything that is "ready for UX". LMK if something else would work better.

**Comment by jeffreywescott** [comment]
Suggestions from Game Mechanics:

## Pool configuration

The moderator passes a **pool threshold config file** to `/cycle init` which defines:

1. The number of different pools
2. The Elo thresholds between pools
3. Advanced players assigned to the pools

For example the config file could define: 

|Pool Elo min|Pool Elo max|Advanced Players|
|----|----|----|
|0|1000|@bluemihai, @jaredtron|
|1001|1100|@shereefb, @tanner|
|1101|9999|@carla, @needdra|

## Project configuration

Once votes are in the Moderator launches the cycle `/cycle launch` passing a **team threshold config file** that defines Elo bands which constrain the maximum number of concurrent projects a player can be on. 

For example, the **team threshold config file** could dictate:

|Elo Threshold|Max Concurrent Projects|
|---|----|
|1000|0|
|1100|1|
|1200|3|
|1500|4|

This means that a player with an ELO rating less than 1000 cannot be assigned as an advanced player to a team. 

A player with an ELO rating of 1150 can be an advanced player on upto 3 concurrent projects.

**Comment by tannerwelsh** [comment]
Proposed moderator UI/UX for configuration.
Feedback please! \cc @LearnersGuild/software @shereefb 

Tried to keep the subcommands straightforward and easy to type, remember, and parse.

**Comment by bundacia** [comment]
I would **strongly** prefer a command that just takes a URL param that points to a yaml file (we could even add param to `/cycle init`). I think that would be a lot simpler to use and much easier to implement. Trying to type this correctly on the first try would be a bit of a pain:

```
/config add --pools id:purple elo_band:2001..9999 advanced_players:[@tannerwelsh, @jeffreywescott]
```

Moderators could use a git gist to host the file which would allow them to reuse configs from cycle to cycle and even track changes.

**Comment by tannerwelsh** [comment]
Roger that @bundacia. I'll update the design with a URL input instead.

Starting to feel like doing any command-based UI design work is comically useless. I agree that pointing to a YAML file is a "better" way to get the data into the system than the design above, and it is also one more glaring hack. Looking forward to designing towards fewer hacks.

**Comment by bundacia** [comment]
Yeah, it's a huge hack. The hackishness is mitigated a little bit in this case by this being a moderator-only command, so at least we're not negatively affecting the UI for the players **and** it contributes toward this benefit:

> As a game designer, I can iterate quickly on the game mechanics

Since this will effectively allow the moderator/game-design to tweak the team formation algorithm in real time.

**Comment by prattsj** [comment]
...sorry if i missed it, but why aren't we just doing this as a form in a web app? no matter what the moderator interface is, the system still has to be able to identify and process specific inputs, so it offers no less flexibility for the moderator than a config file or command line interface would. and it would seem to be the clear winner in terms of usability.

**Comment by tannerwelsh** [comment]
Here's what a web form could look like:

![config 1](https://cloud.githubusercontent.com/assets/709100/17936903/52ef616c-69ee-11e6-8b28-fca7bf1438a7.png)

**Comment by tannerwelsh** [comment]
And what a YAML-file URL provision interface would look like:

```
@moderator  > /config update https://gist.github.com/raw/apeionafdli132r98bae/cycle_config.yaml
@echo       > Cycle config updated! New config settings:
              pools:
               - id: green
                 elo_band: 0..1000
                 advanced_players:
                   - @bundacia
                   - @shereefb
               - id: blue
                 elo_band: 1001..2500
                 advanced_players:
                   - @jeffreywescott
                   - @prattsj
              project_limits:
               elo_0: 1
               elo_1100: 2
               elo_1300: 3
               elo_1500: 4

@moderator  > /config update https://gist.github.com/raw/apeionafdli132r98bae/INVALID_cycle_config.yaml
@echo       > Womp womp. Couldn't parse that config file. 
              Did you verify that it is a valid YAML format, and matches the schema requirements?
```
